name: prova_flutterflow
description: A new Flutter project.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  built_collection: 5.1.1
  built_value: 8.4.3
  cached_network_image: 3.2.1
  cloud_firestore: 4.2.0
  cloud_firestore_platform_interface: 5.9.1
  cloud_firestore_web: 3.1.1
  cloud_functions: 4.0.6
  cloud_functions_platform_interface: 5.1.25
  cloud_functions_web: 4.3.14
  file_picker: 4.5.1
  firebase_auth: 4.2.0
  firebase_auth_platform_interface: 6.11.4
  firebase_auth_web: 5.2.0
  firebase_core: 2.4.0
  firebase_core_platform_interface: 4.5.2
  firebase_core_web: 2.0.2
  flutter_animate: 1.0.0
  flutter_cache_manager: 3.3.0
  flutter_rating_bar: 4.0.1
  flutter_spinkit: 5.1.0
  flutter_stripe: 4.0.0
  flutter_stripe_web: 1.2.0
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  google_fonts: 3.0.1
  google_sign_in: 5.4.0
  google_sign_in_ios: 5.4.0
  google_sign_in_platform_interface: 2.2.0
  google_sign_in_web: 0.10.2
  image_picker: 0.8.5+3
  image_picker_android: 0.8.5+3
  image_picker_for_web: 2.1.10
  image_picker_ios: 0.8.6+1
  image_picker_platform_interface: 2.6.2
  intl: 0.17.0
  json_path: 0.4.1
  json_serializable: 6.6.1
  mime_type: 1.0.0
  page_transition: 2.0.4
  percent_indicator: 4.2.2
  plugin_platform_interface: 2.1.3
  provider: 6.0.4
  rxdart: 0.27.4
  shared_preferences: 2.0.15
  sign_in_with_apple: 4.1.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: 1.0.1
  sqflite: 2.2.0+2
  stripe_android: 4.0.0
  stripe_ios: 4.0.0
  stripe_platform_interface: 4.0.0
  timeago: 3.2.2
  url_launcher: 6.1.5
  video_player: 2.4.5
  video_player_android: 2.3.8
  video_player_avfoundation: 2.3.5
  video_player_platform_interface: 5.1.3
  video_player_web: 2.0.12


dev_dependencies:
  build_runner: 2.3.3
  built_value_generator: 8.4.3
  flutter_launcher_icons: 0.12.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
  